### ISSUE TITLE
401 Unauthorized when listing orders

### ISSUE THREAD

**Issue by rmarriott-db** [fillup/walmart-partner-api-sdk-php#15]
I'm trying to retrieve a list of orders from Walmart. Using v1.0.4 of the SDK, I was able to retrieve the first page of orders, but then when I issued the nextCursor filter, I'd get the following error the next time I called list():

> Fatal error: Call to a member function getStatusCode() on null in C:\xampp\htdocs\walmart\vendor\fillup\walmart-partner-api-sdk-php\src\Order.php on line 124

which happens to be this line of Order.php:

```
public function listAll(array $config = [])
    {
        try {
            return $this->privateList($config);
        } catch (\Exception $e) {
            if ($e instanceof RequestException) {
                /*
                 * ListReleased and List return 404 error if no results are found, even for successful API calls,
                 * So if result status is 404, transform to 200 with empty results.
                 */
                /** @var ResponseInterface $response */
                $response = $e->getResponse();

-----------> if (strval($response->getStatusCode()) === '404') {

                    return [
                        'statusCode' => 200,
                        'list' => [
                            'meta' => [
                                'totalCount' => 0
                            ]
                        ],
                        'elements' => []
```

It appears $response is null?

So, I upgraded to the latest version of the SDK, v1.0.6, hoping there would be a fix. However, I now get a 401 Unauthorized error returned. This is happening on the first list() call.

Below is a basic example of how I'm calling list() and the different response, depending on the version of the SDK. (Note: I've omitted my credentials for security reasons, but the variables, like $consumerId, are all defined in my actual code.)

```
require 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

use Walmart\Order;

$client = new Order([
    'consumerId' => $consumerId,
    'privateKey' => $privateKey,
    'wmConsumerChannelType' => $wmConsumerChannelType
]);

$orders = $client->list([
    'createdStartDate' => '2016-08-30',
    'limit' => 1
]);

print_r($orders);
```

v1.0.4 Output:

```
Array
(
    [statusCode] => 200
    [meta] => Array
        (
            [totalCount] => 2
            [limit] => 1
            [nextCursor] => ?limit=1&hasMoreElements=true&soIndex=1&poIndex=0&partnerId=10000001862&sellerId=1719&createdStartDate=2016-08-30&createdEndDate=2016-09-30T18:11:52.730Z
        )

    [elements] => Array
        (
            [order] => Array
                (
                   ...
```

v1.0.6 Output:

```
Array
(
    [createdStartDate] => 2016-08-30
    [limit] => 1
)

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://marketplace.walmartapis.com/v3/orders?createdStartDate=2016-08-30&limit=1 [status code] 401 [reason phrase] Unauthorized' in C:\xampp\htdocs\walmart\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:89
Stack trace:
#0 C:\xampp\htdocs\walmart\vendor\guzzlehttp\guzzle\src\Subscriber\HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))
#1 C:\xampp\htdocs\walmart\vendor\guzzlehttp\guzzle\src\Event\Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')
#2 C:\xampp\htdocs\walmart\vendor\guzzlehttp\guzzle\src\RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))
#3 C:\xampp\htdocs\walmart\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#4 C:\xamp in C:\xampp\htdocs\walmart\vendor\guzzlehttp\command\src\AbstractClient.php on line 171
```

Please advise if I should be reporting this issue to Walmart. Since different versions are producing different results, I'm thinking the issue is on my end.

Thanks

**Comment by rmarriott-db** [comment]
I seem to be getting the 401 Unauthorized errors with other operations, like bulk creating items, too.

**Comment by rmarriott-db** [comment]
The solution to the 401 Unauthorized errors someone posted in another ticket worked great, but I'm still getting the following error when I fetch the next page of orders with nextCursor:

> Fatal error: Call to a member function getStatusCode() on null in C:\xampp\htdocs\walmart\vendor\fillup\walmart-partner-api-sdk-php\src\Order.php on line 124

This is the code I'm using to page through the orders:

```
$config = json_decode(file_get_contents('walmart-config.json'));

$client = new Order([
    'consumerId' => $config->consumerId,
    'privateKey' => $config->privateKey,
    'wmConsumerChannelType' => $config->wmConsumerChannelType
]);

$nextCursor = '';

do {
    $filters = [
        'createdStartDate' => date('Y-m-d', strtotime('-30 days')),
        'limit' => 1
    ];

    if ('' !== $nextCursor) {
        $filters = [];
        $filters['nextCursor'] = $nextCursor;
    }

    try {
        $orders = $client->list/*Released*/($filters);

        print_r($orders);

        if (0 === $orders['meta']['totalCount']) {
            if ($debug) {
                echo 'No released orders were returned.', PHP_EOL;
            }

            exit();
        }

        // Process orders here...

    } catch (Exception $e) {
        $errorMessage = 'Caught exception: ' . $e->getMessage();

        if ($debug) {
            echo $errorMessage, PHP_EOL;
        }
    }

    if (isset($orders['meta']['nextCursor'])) {
        $nextCursor = $orders['meta']['nextCursor'];
    }
} while ('' !== $nextCursor);

```

TIA!

**Comment by fillup** [comment]
@rmarriott-db sorry for delayed response. It is accurate that you'll get different results, I merged in a PR a couple weeks back that supposedly fixed the nextCursor issue. I don't have access to the Walmart APIs myself anymore so its hard for me to debug, but can you send me some sanitized examples of what the nextCursor values are you're getting so I can do some testing with them? Since the Auth signature is calculated using the full URL being requested I suspect the issue may be with url encoding happening before or after the signature is calculated causing the actual requested url to not match what was used for the signature.

**Comment by rmarriott-db** [comment]
Is this the value you're looking for?

```
?limit=1&hasMoreElements=true&soIndex=1&poIndex=0&partnerId=10000001862&sellerId=1719&createdStartDate=2016-08-30&createdEndDate=2016-09-30T18:11:52.730Z
```

Unfortunately, I only have the two orders on Walmart at the moment, which is why I had to use limit=1 to test order paging. We'll be creating more test orders in the next week, so I'll be able to provide you with more examples then.

If you need more details or the output in another format, please let me know.

Thanks

**Comment by ghost** [comment]
I slove this problem，my pc os is window 10 64bit，php version 5.5.36，in AuthSubscriber.php line 44  update `$timestamp = intval(Utils::getMilliseconds());` to `$timestamp = Utils::getMilliseconds();` , I think millisecond overflow the max size of integer.

**Comment by rmarriott-db** [comment]
Thanks, I made the change you suggested and it fixed the 401 Unauthorized errors. However, I'm still getting another error when I use nextCursor (see above). I'll be doing more order testing this week and will try to isolate the problem and post more details (hopefully a solution).

**Comment by ghost** [comment]
@rmarriott-db  I slove this problem,   in descriptions files update the code `'nextCursor' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'query',
                ],`   to `'nextCursor' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'uri',
                ],`

**Comment by rmarriott-db** [comment]
Thanks! I'll give that a try

**Comment by fillup** [comment]
@qiuxincai1988 the `nextCursor` parameter was already defined as location `uri`, so what were you changing?

I removed the `inval()` call from develop but guess I haven't merged to master and released yet. I'll go ahead and do that shortly though.

**Comment by rmarriott-db** [comment]
My guess is line 29 of order.php, which is the only place that matched his description. However, I tried the suggested change, and I'm still getting the 'method called on null object' error. I'll have to do some debugging to determine what's happening. Unfortunately, I'm currently working on another project, so I probably won't get back to this until next week.

**Comment by fillup** [comment]
Ahh, I see that now, thanks for pointing it out. I updated it to be the same as the `list` call and will get it released shortly. After you've had a chance to verify it works let me know and I'll close out the issue.

**Comment by rmarriott-db** [comment]
I tried qiuxincai1988's suggestion, but it didn't stop the null error. I added some debugging output to the constructor in Guzzle's RequestException.php to show the values of $response and $code.

```
    public function __construct(
        $message,
        RequestInterface $request,
        ResponseInterface $response = null,
        \Exception $previous = null
    ) {
        // Set the code of the exception if the response is set and not future.
        $code = $response && !($response instanceof FutureInterface)
            ? $response->getStatusCode()
            : 0;
        parent::__construct($message, $code, $previous);
        $this->request = $request;
        $this->response = $response;

var_dump($response);
var_dump($code);

    }
```

I currently have four test orders on Walmart and set the limit to 1 order per page, so I should have 4 order pages. When I run the code, the first page outputs the first order data and then the next order page is called. That's where the error occurs.

What I noticed from doing a var_dump() on those two variables is that $response is null and $code is 0 both times the constructor is called.

```
NULL
int(0)

NULL
int(0)
```

which explains why the code crashes here:

```
                $response = $e->getResponse();
                if (strval($response->getStatusCode()) === '404') {
```

Unfortunately, I'm new to Guzzle, so that's as far as I've gotten on debugging this.

**Comment by ajbonner** [comment]
We've run into this too, the issue I found was that guzzle is url encoding the ':' symbol in urls, but the walmart library is generating a signature on an unencoded url. This obviously results in different signatures.

On walmart's end they must be calculating the signature on the encoded url and not a decoded one.

So for example the signature for https://marketplace.walmartapis.com/v3/orders/released?limit=10&hasMoreElements=true&soIndex=10&poIndex=0&partnerId=100000&sellerId=1234&status=Created&createdStartDate=2010-01-01&createdEndDate=2016-11-01T13%3A39%3A24.377Z 

is different to

 https://marketplace.walmartapis.com/v3/orders/released?limit=10&hasMoreElements=true&soIndex=10&poIndex=0&partnerId=100000&sellerId=1234&status=Created&createdStartDate=2010-01-01&createdEndDate=2016-11-01T13:39:24.377Z 

Interestingly (and I apologise for missing any context here) this problem appears to be because of 

``` php
// in file vendor/fillup/walmart-partner-api-sdk-php/src/middleware/AuthSubscriber.php
//decode url back to normal to nextCursor issue. automatic url encoding
$requestUrl = rawurldecode($requestUrl);
$event->getRequest()->setUrl($requestUrl);
```

This is what's breaking signatures for nextcursor in our case. _Commenting that out everything works._ This is on PHP 7.

This is the commit that introduced the issue -https://github.com/fillup/walmart-partner-api-sdk-php/commit/5165c2f0d07e5b180793341a33b10e0f3180a8be#diff-cca7dba5d3a2bf5e41fcc87f70fa80f7

Wonder if something has changed since in Guzzle, or the way Walmart were verifying signatures since.

**Comment by rmarriott-db** [comment]
Interesting! I've managed to trap the error messages everywhere my code crashes. In each case, whether I'm trying to get the second page of orders or attempting to acknowledge or refund an order, whenever an exception is thrown this seems to be the error message: "Http client is missing 'auth' parameters". This is in AuthSubscriber.php in addAuthHeaders(), I believe. Does anyone know of a work-around? Thanks

**Comment by rmarriott-db** [comment]
Yes, you are correct, ajbonner. The 'auth' parameter issue I encountered was my fault. I wasn't recreating the $client object in every iteration. Once I restructured my code, I ran into the issue you're referring to. I commented out those two lines in AuthSubscriber, and listing orders appears to be working now.

**Comment by fillup** [comment]
@rmarriott-db @ajbonner sorry for the weird use of `auth` parameter with guzzle, it was the only way I could figure to pass the key/cert into my middleware for calculating the signature at call time since the signature requires the full url as well. That is interesting note about how Walmart may be calculating the signature pre or post encoding. Are you still experiencing problems with that? I'll reach out to a contact there and see if I can get the correct answer and update the code.

**Comment by rmarriott-db** [comment]
Thanks, @fillup. I actually had a few issues going on at the same time when I created this ticket. One was caused by our not recreating the $client object on each iteration. I've since fixed that in our code.

The other issue occurred when using nextCursor. I was able to get it to work by commenting out the two lines in src/middleware/AuthSubscriber.php, as suggested by @ajbonner:

```
//decode url back to normal to nextCursor issue. automatic url encoding
//$requestUrl = rawurldecode($requestUrl);  <----- line 40
//$event->getRequest()->setUrl($requestUrl); <----- line 41
```

If I don't comment out those two lines, then I won't be able to fetch the next page of orders. So I think it would be a good idea to remove those two lines from the next version of the SDK. Walmart probably changed the way the API works since that logic was written.

**Comment by fillup** [comment]
Ok sure, if that change is working for you guys I'll go ahead and make it in the library as well.

**Comment by rmarriott-db** [comment]
Great thanks, @fillup!

**Comment by ajbonner** [comment]
Yeah, we have a private fork with the two lines commented out. The library doesn't work with them still there. I wonder if a bug fix on Walmart's side rendered that code redundant as it makes sense to generate the signature on the url as it is received rather than one that's been parsed/decoded.

**Comment by fillup** [comment]
Ok, I have an email in to the API team at Walmart for a definitive answer on how they evaluate the url for calculating signature. Then I'll make sure this library does it the same way and get it updated.

**Comment by jnitishkr** [comment]
Hi,

I am trying to fetch all item but i am getting error "Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://marketplace.walmartapis.com/v2/items?sku=&limit=5&offset=0 [status code] 401 [reason phrase] Unauthorized' in /home/jvgtechc/public_html/platformconnection/walmart-partner-api-sdk-php-develop/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /home/jvgtechc/public_html/platformconnection/walmart-partner-api-sdk-php-develop/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /home/jvgtechc/public_html/platformconnection/walmart-partner-api-sdk-php-develop/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /home/jvgtechc/public_html/platformconnection/walmart-partner-api-sdk-php-develop/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\ in /home/jvgtechc/public_html/platformconnection/walmart-partner-api-sdk-php-develop/vendor/guzzlehttp/command/src/AbstractClient.php on line 172".


**Please help me to figure out this issue.**

**Comment by LevelDisk** [comment]
Same issue, I triple checked the consumerId, privateKey, and wmConsumerChannelType. $client has all the values after it's created. I checked with and without wmConsumerChannelType. It's the same consumerId and privateKey that is working with ShipRush; I copied and pasted it over. Getting a 401 on all API calls (list items, list orders, list feeds)

```
use Walmart\Item;

$client = new Item([
  'consumerId' => $settings['walmartConsumerId'],
  'privateKey' => $settings['walmartPrivateKey'],
  'wmConsumerChannelType' => $settings['walmartChannelType'],
]);

try {
	$resultsArr = $client->list([

	]);
}
catch (Exception $e) {
  die("There was a problem requesting the data: ".$e->getMessage());
}
```

**Comment by LevelDisk** [comment]
Fixed it by adding the intval() back in to AuthSubscriber.php on line 44:

`        $timestamp = intval(Utils::getMilliseconds());`

So it looks like the update from before (that removed intval) broke it for me

**Comment by hamiltonnieri8755** [comment]
@fillup Fixed it by adding the intval() back in to AuthSubscriber.php on line 44:

$timestamp = intval(Utils::getMilliseconds());

**Comment by houchengli** [comment]
The solution is here urlencode any of date param would be OK, That's all!
